language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - "~/.m2/repository"

before_install:
  - "./.travis/before-install.sh"

install:
  - "./.travis/install.sh"

script:
  - "./.travis/test.sh"

after_success:
  - "./.travis/deploy.sh"
